# Generated by Django 4.1 on 2023-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_f',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
