# Generated by Django 4.1 on 2023-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('imagecontent', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
